apiVersion: v1
kind: Service
metadata:
  name: datacontrol-frontend
  namespace: datacontrol
  labels:
    app: datacontrol
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      name: nginx
  selector:
    app: datacontrol-app
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datacontrol-frontend
  namespace: datacontrol
spec:
  selector:
    matchLabels:
      app: datacontrol-app
      tier: frontend
  replicas: 1
  template:
    metadata:
      namespace: datacontrol
      labels:
        app: datacontrol-app
        tier: frontend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: frontend
          image: docker.io/library/data-control-app-frontend:latest
          imagePullPolicy: Never
          env:
            - name: MY_APP_USER_HOST
              value: http://datacontrol.app
          ports:
            - containerPort: 80
              name: frontend