apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: datacontrol
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-app
  namespace: datacontrol
  labels:
    app: postgres-app
spec:
  selector:
    matchLabels:
      app: postgres-app # has to match .spec.template.metadata.labels
  serviceName: "postgres"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      namespace: datacontrol
      labels:
        app: postgres-app # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: docker.io/library/data-control-app-postgres:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              value: database
            - name: POSTGRES_PASSWORD
              value: secret
            - name: POSTGRES_USER
              value: myuser

  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 4Gi